#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


#runParallel $(getApplication)
bsub -q cresco6_h144 -e err.txt -J '2inlet_V2' rhoCentralFoam 

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
